# Generated by Django 2.1.5 on 2020-06-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogger',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=30)),
                ('msg', models.TextField()),
                ('re_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
