# Generated by Django 2.1.5 on 2020-06-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_blogcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontent',
            name='slug',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
